photoGallery/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace photoGallery.Models
{
    public class Photo
    {
        [Key]
        public int ID { get; set; }
        
        [Required(ErrorMessage = "An Album Title is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Title must be between 3 and 50 characters!")]
        public string Title{get;set;}

        [ScaffoldColumn(false)]
        public string ImageName { get; set; }
        [NotMapped]
        public HttpPostedFileBase File { get; set; }

        [ScaffoldColumn(false)]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Inserted Date ")]
        public DateTime? InsertedDateTime { get; set; }

        [ScaffoldColumn(false)]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? LastUpdatedDatetime { get; set; }

        [ScaffoldColumn(false)]
        public string InsertedBy { get; set; }
        [ScaffoldColumn(false)]
        public string LastUpdatedBy { get; set; }

        public int AlbumId { get; set; }
        public virtual Album Album { get; set; }
    }
}

photoGallery/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using photoGallery.Models;
using System.IO;

namespace photoGallery.Controllers
{
    [HandleError]
    public class PhotosController : Controller
    {
        private GalleryContext db = new GalleryContext();

        // GET: Photos
         [HandleError]
        public ActionResult Index()
        {                      
            var photos = db.Photos.Include(p => p.Album);
            return View(photos.ToList());
        }
        
        public ActionResult filterPhoto(int albamId) 
        {
            var photos = db.Photos.Include(p => p.Album);
            photos = photos.Where(c => c.AlbumId == albamId);
            return View("PhotoIndex",photos.ToList());
        }
        public ActionResult Manage()
        {
            var photos = db.Photos.Include(p => p.Album);
            return View("ManagePhoto",photos.ToList());
        }
        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            ViewBag.AlbumId = new SelectList(db.ImageGalleries, "ID", "AlbumName");
            return View();
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,AlbumId")] Photo photo, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Message"] = "";
                    var filename = "";
                    if (file != null && file.ContentLength > 0)
                    {
                        Guid gid;
                        gid = Guid.NewGuid();
                        var extension = Path.GetExtension(file.FileName);
                        filename = gid + extension;

                        var path = Path.Combine(Server.MapPath("~/Content/PhotoGallery/" + setAlbumName(photo.AlbumId)), filename);

                        var data = new byte[file.ContentLength];
                        file.InputStream.Read(data, 0, file.ContentLength);

                        using (var sw = new FileStream(path, FileMode.Create))
                        {
                            sw.Write(data, 0, data.Length);
                        }
                    }
                    photo.ImageName = filename;
                    photo.InsertedDateTime = DateTime.Now;
                    photo.InsertedBy = User.Identity.Name;
                    db.Photos.Add(photo);
                    db.SaveChanges();
                    TempData["Message"] = "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a><strong>Success!</strong> Successfully Save.</div> ";
                }
                catch (Exception ex)
                {

                    TempData["Message"] = "<div class='alert alert-danger'><a href='#' class='close' data-dismiss='alert'>&times; Directory</a><strong> " + ex.ToString() + "</strong> Not found.</div>";
                }
                return RedirectToAction("Index");
            }

            ViewBag.AlbumId = new SelectList(db.ImageGalleries, "ID", "AlbumName", photo.AlbumId);
            return View(photo);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            ViewBag.AlbumId = new SelectList(db.ImageGalleries, "ID", "AlbumName", photo.AlbumId);
            return View(photo);
        }

        // POST: Photos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,AlbumId")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Message"] = "";

                    db.Entry(photo).State = EntityState.Modified;
                    db.Entry(photo).Property("InsertedBy").IsModified = false;
                    db.Entry(photo).Property("InsertedDateTime").IsModified = false;
                    db.Entry(photo).Property("ImageName").IsModified = false;
                    string path = Server.MapPath("~/Content/PhotoGallery/");
                    var ImageName = GetImageName(photo.ID);
                    string Fromfol = GetAlbumNameByPhotoID(photo.ID) + "/" + ImageName;
                    string Tofol = setAlbumName(photo.AlbumId) + "/" + ImageName;
                    photo.LastUpdatedBy = User.Identity.Name;
                    photo.LastUpdatedDatetime = DateTime.Now;
                    System.IO.File.Move(path + Fromfol, path + Tofol);                    
                    db.SaveChanges();
                    TempData["Message"] = "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a><strong>Success!</strong> Successfully Edited.</div> ";
                }
                catch (IOException ex)
                {

                    TempData["Message"] = "<div class='alert alert-danger'><a href='#' class='close' data-dismiss='alert'>&times; </a><strong> " + ex.ToString() + "</strong> </div>";
                }
                return RedirectToAction("Index");
            }
            ViewBag.AlbumId = new SelectList(db.ImageGalleries, "ID", "AlbumName", photo.AlbumId);
            return View(photo);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photo photo = db.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Photo photo = db.Photos.Find(id);
                var path = Server.MapPath("~/Content/PhotoGallery/" + photo.Album.AlbumName);
                var filename = Path.Combine(Server.MapPath("~/Content/PhotoGallery/" + photo.Album.AlbumName), photo.ImageName);
                if (directoryExists(path))
                {

                    System.IO.File.Delete(filename);
                    db.Photos.Remove(photo);
                    db.SaveChanges();
                    TempData["Message"] = "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a><strong>Success!</strong> Successfully deleted.</div> ";
                }
                else
                {
                    TempData["Message"] = "<div class='alert alert-danger'><a href='#' class='close' data-dismiss='alert'>&times; Directory</a><strong> " + photo.Album.AlbumName + "</strong> Not found.</div>";
                }
            }
            catch (IOException ex)
            {
                TempData["Message"] = "<div class='alert alert-danger'><a href='#' class='close' data-dismiss='alert'>&times; </a><strong> " + ex.ToString() + "</strong> </div>";
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private string setAlbumName(int ID) {

            Album abl = null;
            using (GalleryContext Newdb = new GalleryContext())
            {
                abl = (from s in Newdb.ImageGalleries
                       where s.ID == ID
                       select s).FirstOrDefault();

            }
            return abl.AlbumName;
        }

        private string GetAlbumNameByPhotoID(int ID)
        {

            var albumName = "";
            using (GalleryContext Newdb = new GalleryContext())
            {
                var photos = Newdb.Photos.Include(p => p.Album);
                photos = photos.Where(c => c.ID == ID);
                if (photos.Count() > 0)
                {
                    albumName = photos.FirstOrDefault().Album.AlbumName;
                }
            }
            return albumName;
        }

        private string GetImageName(int ID)
        {

            var ImageName = "";
            using (GalleryContext Newdb = new GalleryContext())
            {
                var Photos = (from s in Newdb.Photos
                              where s.ID == ID
                              select s);
                if (Photos.Count() > 0)
                {
                    ImageName = Photos.FirstOrDefault().ImageName;
                }
            }
            return ImageName;
        }

        private bool directoryExists(string path)
        {
            return Directory.Exists(path);

photoGallery/Views/Photos/Create.cshtml
@model photoGallery.Models.Photo

@{
   // ViewBag.Title = "Create";
}

@*<h2>Create</h2>*@


@using (Html.BeginForm("Create", "Photos", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Add Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="file" class="control-label col-md-2">Select a file: </label>

            <div class="col-md-10">
                <input type="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumId, "AlbumId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlbumId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Back to List", "Back to List", "Index", "Photos", "glyphicon-backward", null, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

photoGallery/Views/Photos/Delete.cshtml
@model photoGallery.Models.Photo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Album.AlbumName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.AlbumName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-info btn-small" /> |
            @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Back to List", "Back to List", "Index", "Photos", "glyphicon-backward", null, null)
        </div>
    }
</div>

photoGallery/Views/Photos/Details.cshtml
@model photoGallery.Models.Photo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Photo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Album.AlbumName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Album.AlbumName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>
</div>
<p>
    
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Back to List", "Back to List", "Index", "Photos", "glyphicon-backward", null, null)
</p>

photoGallery/Views/Photos/Edit.cshtml
@model photoGallery.Models.Photo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Photo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AlbumId, "AlbumId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AlbumId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AlbumId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info btn-small" />
            </div>
        </div>
    </div>
}

<div>
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Back to List", "Back to List", "Index", "Photos", "glyphicon-backward", null, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

photoGallery/Views/Photos/Index.cshtml
@model IEnumerable<photoGallery.Models.Photo>

@{
   // ViewBag.Title = "Index";
}

@Html.Raw(TempData["Message"])
<p>
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Add Photo", "Add Photo", "Create", "Photos", "glyphicon-plus", null, null)
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Manage Photo", "Manage Photo", "Manage", "Photos", "glyphicon-plus", null, null)
</p>




<div class="row" style=" margin-top: 0px;">
    @foreach (var item in Model)
    {
        <div class="col-sm-6 col-md-3">
            @{
                <p>
                    <a href="@(Url.Content("~/Content/PhotoGallery/" + item.Album.AlbumName + "/" + item.ImageName))" title="@Html.DisplayFor(modelItem => item.Title)" data-gallery="" class="thumbnail">
                        <img src="@(Url.Content("~/Content/PhotoGallery/" + item.Album.AlbumName + "/" + item.ImageName))" border="0" style="border: 0px" class="img-thumbnail" />
                    </a>
                </p>
            }
        </div>
    }
</div>
    <!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
        <!-- The container for the modal slides -->
        <div class="slides"></div>
        <!-- Controls for the borderless lightbox -->
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
        <!-- The modal dialog, which will be used to wrap the lightbox content -->
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body next"></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary pull-left prev">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                            Previous
                        </button>
                        <button type="button" class="btn btn-primary next">
                            Next
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

photoGallery/Views/Photos/ManagePhoto.cshtml
@model IEnumerable<photoGallery.Models.Photo>

@{
   // ViewBag.Title = "Index";
}



<br />
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Album.AlbumName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InsertedDateTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Album.AlbumName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InsertedDateTime)
            </td>
            <td>
                @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "", "Edit", "Edit", "Photos", "glyphicon-pencil", new { id = item.ID }, null) &nbsp;
                @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "", "Details", "Details", "Photos", "glyphicon-list", new { id = item.ID }, null) &nbsp;
                @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "", "Delete", "Delete", "Photos", "glyphicon-floppy-remove", new { id = item.ID }, null)
            </td>
        </tr>
    }

</table>

photoGallery/Views/Photos/PhotoIndex.cshtml
@model IEnumerable<photoGallery.Models.Photo>

@{
//    ViewBag.Title = "Index";
}


<p>
    @*@photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Add Photo", "Add Photo", "Create", "Photos", "glyphicon-plus", null, null)*@
</p>
<div class="row" style=" margin-top: 0px;">
    @foreach (var item in Model)
    {
        //col-sm-6 col-md-3
        <div class="col-sm-6 col-md-3">
            @{
                <p>
                    <a href="@(Url.Content("~/Content/PhotoGallery/" + item.Album.AlbumName + "/" + item.ImageName))" title="@Html.DisplayFor(modelItem => item.Title)" data-gallery="" class="thumbnail">
                        <img src="@(Url.Content("~/Content/PhotoGallery/" + item.Album.AlbumName + "/" + item.ImageName))" class="img-responsive" />
                    </a>
                </p>

            }
        </div>
    }
</div>
<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>