photoGallery/Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace photoGallery.Models
{
    public class Album
    {
        [Key]
        public int ID { get; set; }

        [DisplayName("Albam Name ")]
        [Required(ErrorMessage = "An Album Title is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Albam Name must be between 3 and 50 characters!")]
        public string AlbumName { get; set; }

        [ScaffoldColumn(false)]
        public string ThumbnailImage { get; set; }
        [NotMapped]
        public HttpPostedFileBase File { get; set; }

        [ScaffoldColumn(false)]
        [DataType(DataType.Date)]
        [DisplayName("Inserted Date ")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? InsertedDateTime { get; set; }

        [ScaffoldColumn(false)]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? LastUpdatedDatetime { get; set; }

        [ScaffoldColumn(false)]
        public string InsertedBy { get; set; }
        [ScaffoldColumn(false)]
        public string LastUpdatedBy { get; set; }

        public virtual List<Photo> Photos { get; set; }
    }
}

photoGallery/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using photoGallery.Models;
using System.IO;

namespace photoGallery.Controllers
{
    public class AlbumsController : Controller
    {
        private GalleryContext db = new GalleryContext();

        // GET: Albums
        public ActionResult Index()
        {            
            return View(db.ImageGalleries.ToList());
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.ImageGalleries.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Albums/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AlbumName,InsertedDateTime,LastUpdatedDatetime,InsertedBy,LastUpdatedBy")] Album album)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = "";                
                var path = Server.MapPath("~/Content/PhotoGallery/" + album.AlbumName);
                Directory.CreateDirectory(path);
                db.ImageGalleries.Add(album);
                album.InsertedDateTime = DateTime.Now;
                album.InsertedBy = User.Identity.Name;
                db.SaveChanges();
                TempData["Message"] = "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a><strong>Success!</strong> Successfully Save.</div> ";
                return RedirectToAction("Index");
            }

            return View(album);
        }

        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.ImageGalleries.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,AlbumName,InsertedDateTime,LastUpdatedDatetime,InsertedBy,LastUpdatedBy")] Album album)
        {
            if (ModelState.IsValid)
            {
                TempData["Message"] = "";
                db.Entry(album).State = EntityState.Modified;
                album.LastUpdatedBy = User.Identity.Name;
                album.LastUpdatedDatetime = DateTime.Now;
                db.Entry(album).Property("InsertedBy").IsModified = false;
                db.Entry(album).Property("InsertedDateTime").IsModified = false;
                
                string path = Server.MapPath("~/Content/PhotoGallery/");             
                string Fromfol = getAlbamName(album.ID);
                string Tofol = album.AlbumName;
                if (directoryExists(path + Fromfol))
                {
                    Directory.Move(path + Fromfol, path + Tofol);
                    db.SaveChanges();
                    TempData["Message"] = "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a><strong>Success!</strong> Successfully renamed.</div> ";
                }
                else {
                    TempData["Message"] = "<div class='alert alert-danger'><a href='#' class='close' data-dismiss='alert'>&times; Directory</a><strong> " + Fromfol + "</strong> Not found.</div>";
                }                                
                return RedirectToAction("Index");
            }
            return View(album);
        }

        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.ImageGalleries.Find(id);

            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TempData["Message"] = "";
            Album album = db.ImageGalleries.Find(id);
            db.ImageGalleries.Remove(album);
            var path = Server.MapPath("~/Content/PhotoGallery/" + album.AlbumName);
            if (directoryExists(path))
            {
                Directory.Delete(path, true);
                db.SaveChanges();
                TempData["Message"] = "<div class='alert alert-success'><a href='#' class='close' data-dismiss='alert'>&times;</a><strong>Success!</strong> Successfully deleted.</div> ";
            }
            else
            {
                TempData["Message"] = "<div class='alert alert-danger'><a href='#' class='close' data-dismiss='alert'>&times; Directory</a><strong> " + album.AlbumName + "</strong> Not found.</div>";
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private string getAlbamName(int Id)
        {
            Album abl = null;           
            using (GalleryContext Newdb = new GalleryContext())
            {
                abl = (from s in Newdb.ImageGalleries
                        where s.ID == Id
                        select s).FirstOrDefault();

            }
            return abl.AlbumName;
        }
        private bool directoryExists( string path)
        {
            return Directory.Exists(path);
        }
    }
}

photoGallery/Views/Albums/Create.cshtml
@model photoGallery.Models.Album

@{
    //ViewBag.Title = "Create";
}

<h2>Create New Album</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AlbumName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info btn-small" />
            </div>
        </div>
    </div>
}

<div>    
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Back to List", "Back to List", "Index", "Albums", "glyphicon-backward", null, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

photoGallery/Views/Albums/Delete.cshtml
@model photoGallery.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AlbumName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AlbumName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-info btn-small" /> |
            @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Back to List", "Back to List", "Index", "Albums", "glyphicon-backward", null, null)
        </div>
    }
</div>

photoGallery/Views/Albums/Details.cshtml
@model photoGallery.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AlbumName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InsertedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InsertedDateTime)
        </dd>
    </dl>
</div>
<p>
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "", "Edit", "Edit", "Albums", "glyphicon-backward", new { id = Model.ID }, null) &nbsp;    
    @Html.ActionLink("Back to List", "Index")
</p>

photoGallery/Views/Albums/Edit.cshtml
@model photoGallery.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info btn-small" />
            </div>
        </div>
    </div>
}

<div>
    @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Back to List", "Back to List", "Index", "Albums", "glyphicon-backward", null, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

photoGallery/Views/Albums/Index.cshtml
@model IEnumerable<photoGallery.Models.Album>

@{
  //  ViewBag.Title = "Index";
    
}
@Html.Raw(TempData["Message"])

@*<p><a href="@Url.Action("Edit", new { id = 1 })"><i class="glyphicon glyphicon-pencil" title="Edit"></i><span class="sr-only">Edit</span></a></p>
@Html.ActionLink("Create New Album", "Edit", new { id = 1 }, new { @class = "glyphicon glyphicon-pencil" })*@
@photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "Create New Album", "Create New Album", "Create", "Albums", "glyphicon-plus", null, null)

<div>&nbsp;</div>
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AlbumName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InsertedDateTime)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlbumName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InsertedDateTime)
            </td>
            <td>
                @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "", "Edit", "Edit", "Albums", "glyphicon-pencil", new { id = item.ID }, null) &nbsp;
                @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "", "Details", "Details", "Albums", "glyphicon-list", new { id = item.ID }, null) &nbsp;
                @photoGallery.Utility.Utility4photoGallery.bootstrapActionLink(null, "", "Delete", "Delete", "Albums", "glyphicon-floppy-remove", new { id = item.ID }, null)
            </td>
        </tr>
    }

</table>